### PR TITLE
Update to latest version of NHS.UK frontend (4.0.0) 

### PR DESCRIPTION
**Pull request by pflynny**
I started updating the Wagtail NHS.UK frontend with the latest version of the [NHS.UK frontend](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#400---26-october-2020), getting search live put this on the back burner, but it's time to get it deployed. 

It's mainly tidying up and documentation left to complete, with @AdamChrimes tackling the build for the new tag component. 

I'll tidy up my last few bits this week.

## Done
- [x]  Update to v4.0.0 CSS and JavaScript
- [x]  Remove Panel and Promo components to be replaced with the [Card component](https://service-manual.nhs.uk/design-system/components/card) (@pflynny)
- [x]  Look at the Warning callout default "Important" prefix

## To do
- [ ]  Add [Tag component](https://service-manual.nhs.uk/design-system/components/tag) (@AdamChrimes)
- [x]  Add custom search API endpoint to the example app
- [x]  Add example data to the test app to show how the new card components can be used

### CODE REVIEW

**Comment by mikemonteith** [comment]
- [ ] Documentation: card.md docs need updating with correct headings and examples
- [ ] Documentation: components/README.md needs a link to card.md
- [ ] Documentation: Add deprecation notice to deprecated Panel components
- [ ] Documentation: Add docs for using raw templates as well as blocks
- [ ] Delete old frontend library v3 CSS and JS
- [ ] visually_hidden_prefix help text doesn't sound right. Makes it seem like something automatic is going to happen if the title doesn't contain the word "Important".
- [ ] Details expander contents has visual bug on the testapp

**Comment by pflynny** [comment]
@mikemonteith I've tidied up those bits you mentioned, as well as a few other tidy ups – can you have a look when you get a chance.

**Review by pflynny — COMMENTED** [review]
Looks good

**Review by pflynny — COMMENTED** [review]
Good call on breaking them out to individual blocks, I was unsure about having them nested under the one card block.

**Review by pflynny — COMMENTED** [review]
I thought it might be best to make sure people adhere to the style guide, but makes sense leaving it free for people to the implementors.

**Review by mikemonteith — APPROVED** [review]

**Pull request merged**
