### PR TITLE
update css to frontend release 2.1.0

### PR DESCRIPTION
**Pull request by Ross-Clark**
update setup.py to accept latest css file

### CODE REVIEW

**Comment by Ross-Clark** [comment]
The only HTML changes i could see were for the hero component, which has been update in its own branch and is waiting for a merge

**Comment by AdamChrimes** [comment]
@Ross-Clark would you be able to update the JavaScript version to match?

**Comment by Ross-Clark** [comment]
> @Ross-Clark would you be able to update the JavaScript version to match?
> 
> https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/static/wagtailnhsukfrontend/js/nhsuk-1.0.0.min.js

thank you for catching this

**Comment by AdamChrimes** [comment]
Changes look OK to me, I’m sure if there’s any other HTML changes we will pick them up once we’ve got an instance up and running.

I’ll let Mike have a quick look!

**Pull request merged**
